#!/bin/sh

mkdir ~/.laptop
cd ~/.laptop

curl --remote-name https://raw.githubusercontent.com/dlucian/laptop/master/mac
curl --remote-name https://raw.githubusercontent.com/dlucian/laptop/master/Brewfile

/usr/bin/env bash mac 2>&1 | tee ~/.laptop/laptop.log
